-- CRIME : TABLE FOR CHICAGO_CRIME
-- CENSUS : TABLE FOR CHICAGO CENSUS DATA
-- SCHOOL : TABLE FOR CHICAGO SCHOOL DATA

SELECT SCHOOLS.NAME_OF_SCHOOL, SCHOOLS.COMMUNITY_AREA_NAME, SCHOOLS.AVERAGE_STUDENT_ATTENDANCE
FROM SCHOOLS LEFT JOIN CENSUS
ON SCHOOLS.COMMUNITY_AREA_NUMBER = CENSUS.COMMUNITY_AREA_NUMBER
WHERE CENSUS.HARDSHIP_INDEX=98 ;

SELECT CENSUS.COMMUNITY_AREA_NAME, CRIME.CASE_NUMBER, CRIME.PRIMARY_TYPE
FROM CENSUS
LEFT JOIN CRIME ON CENSUS.COMMUNITY_AREA_NUMBER = CRIME.COMMUNITY_AREA_NUMBER
WHERE UPPER(CRIME.LOCATION_DESCRIPTION) LIKE '%SCHOOL%';

CREATE VIEW CPS_VIEW(
SCHOOL_NAME,
SAFETY_RATING,
LEADERS_RATING,
TEACHERS_RATING) AS
SELECT
NAME_OF_SCHOOL,
SAFETY_ICON,
LEADERS_ICON,
TEACHERS_ICON
FROM SCHOOLS;
--SELECT (*) FROM CPS_VIEW;

SELECT SCHOOL_NAME, LEADERS_RATING FROM CPS_VIEW;

--#SET TERMINATOR @
CREATE OR REPLACE PROCEDURE UPDATE_LEADER_SCORE(
IN in_SCHOOL_ID INTEGER, IN in_LEADER_SCORE INTEGER)

LANGUAGE SQL
MODIFIES SQL DATA

BEGIN
	UPDATE SCHOOLS
	SET LEADERS_SCORE = in_LEADER_SCORE
	WHERE SCHOOL_ID = in_SCHOOL_ID;
	
	IF in_LEADER_SCORE > 0 AND in_LEADER_SCORE < 20 THEN
	UPDATE SCHOOLS SET LEADERS_ICON = 'VERY WEAK'	WHERE SCHOOL_ID = in_SCHOOL_ID;
	ELSEIF in_LEADER_SCORE < 40 THEN
	UPDATE SCHOOLS SET LEADERS_ICON = 'WEAK' WHERE SCHOOL_ID = in_SCHOOL_ID;
	ELSEIF in_LEADER_SCORE < 60 THEN
	UPDATE SCHOOLS SET LEADERS_ICON = 'AVERAGE'	WHERE SCHOOL_ID = in_SCHOOL_ID;
	ELSEIF in_LEADER_SCORE < 80 THEN
	UPDATE SCHOOLS SET LEADERS_ICON = 'STRONG'	WHERE SCHOOL_ID = in_SCHOOL_ID;
	ELSEIF in_LEADER_SCORE < 100 THEN
	UPDATE SCHOOLS SET LEADERS_ICON = 'VERY STRONG' WHERE SCHOOL_ID = in_SCHOOL_ID;
	ELSE ROLLBACK WORK;
	END IF;
	COMMIT WORK;
END
@